package com.agentops.guardian.governance.audit;

public enum AuditEventType {
    PROPOSED_ACTION,
    POLICY_DECISION,
    RISK_ASSESSMENT,
    INTERVENTION_CREATED,
    INTERVENTION_APPROVED,
    INTERVENTION_REJECTED,
    INTERVENTION_EXPIRED,
    EXECUTION_OUTCOME,
    WORKFLOW_TRANSITION
}
